name = "c0-boole"
version = "0.1.0"
defaultTargets = ["c0-boole"]

[[lean_lib]]
name = "C0Boole"

[[lean_exe]]
name = "c0-boole"
root = "Main"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"