name = "c0-boole"
version = "0.1.0"
defaultTargets = ["c0b"]

[[lean_lib]]
name = "C0Boole"

[[lean_exe]]
name = "c0b"
root = "Top"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"