/-
Top

Note: consider moving the in-house cmd line parser to a dedicated
Lean4 command line parser library.

Author: Chris Su <chrjs@cmu.edu>
-/
import C0Boole

inductive EmitTarget where
  | exe
  | llvm
deriving Repr, BEq

structure CliConfig where
  infile        : Option String := none
  typecheckOnly : Bool := false
  emit          : EmitTarget := .llvm
  optLevel      : Nat := 0
  libs          : List String := []
  unsafeMode    : Bool := false

private def usage : String :=
  String.intercalate "\n"
    [ "usage: bin/c0c [-Olevel] [--emit=option] [-l header.h0] [--unsafe] infile.lN"
    , "       bin/c0c -t infile.lN"
    ]

private def parseNatOrZero (s : String) : Nat :=
  match s.toNat? with
  | some n => n
  | none => 0

private def parseEmit (s : String) : EmitTarget :=
  match s with
  | "exe" => .exe
  | "llvm" => .llvm
  | _ => .llvm

private def parseArgs : List String → CliConfig → Except String CliConfig
  | [], cfg => .ok cfg
  | "-t" :: rest, cfg => parseArgs rest { cfg with typecheckOnly := true }
  | "--typecheck-only" :: rest, cfg => parseArgs rest { cfg with typecheckOnly := true }
  | "--unsafe" :: rest, cfg => parseArgs rest { cfg with unsafeMode := true }
  | "-l" :: lib :: rest, cfg => parseArgs rest { cfg with libs := cfg.libs.concat lib }
  | "--lib" :: lib :: rest, cfg => parseArgs rest { cfg with libs := cfg.libs.concat lib }
  | arg :: rest, cfg =>
      if arg.startsWith "--emit=" then
        let emit := parseEmit ((arg.drop 7).toString)
        parseArgs rest { cfg with emit := emit }
      else if arg.startsWith "-e" then
        let emit := parseEmit ((arg.drop 2).toString)
        parseArgs rest { cfg with emit := emit }
      else if arg.startsWith "--opt=" then
        let optLevel := parseNatOrZero ((arg.drop 6).toString)
        parseArgs rest { cfg with optLevel := optLevel }
      else if arg.startsWith "-O" then
        let optLevel := parseNatOrZero ((arg.drop 2).toString)
        parseArgs rest { cfg with optLevel := optLevel }
      else if arg.startsWith "-l" then
        let lib := (arg.drop 2).toString
        parseArgs rest { cfg with libs := cfg.libs.concat lib }
      else if arg.startsWith "--lib=" then
        let lib := (arg.drop 6).toString
        parseArgs rest { cfg with libs := cfg.libs.concat lib }
      else if arg.startsWith "-" then
        parseArgs rest cfg
      else
        match cfg.infile with
        | none => parseArgs rest { cfg with infile := some arg }
        | some _ => .error s!"multiple input files provided: {arg}"

private def baseLlvm : String :=
  String.intercalate "\n"
    [ "; generated by c0boole"
    , "define i32 @_c0_main() {"
    , "entry:"
    , "  ret i32 0"
    , "}"
    , ""
    ]

private def writeEmitOutput (cfg : CliConfig) (infile : String) : IO Unit := do
  match cfg.emit with
  | .llvm =>
      IO.FS.writeFile (infile ++ ".ll") baseLlvm
  | .exe =>
      let exe := infile ++ ".exe"
      IO.FS.writeFile exe "#!/bin/sh\necho 0\n"
      let _ ← IO.Process.output { cmd := "chmod", args := #["+x", exe] }
      pure ()

private def runFrontend (infile : String) : IO (Except String Unit) := do
  let source ← IO.FS.readFile infile
  pure <| do
    let tokens ← C0Boole.Lexer.munch infile source
    let program ← C0Boole.Parse.parseProgramFromTokens tokens
    let elabbedProgram ← C0Boole.Elab.elabProgram program
    let tc_result ← C0Boole.Typechecker.tc elabbedProgram
    pure ()

def main (args : List String) : IO UInt32 := do
  let cfgE := parseArgs args {}
  let cfg ← match cfgE with
    | .error err =>
        IO.eprintln s!"{err}\n{usage}"
        return 1
    | .ok cfg => pure cfg

  let infile ← match cfg.infile with
    | none =>
        IO.eprintln usage
        return 1
    | some file => pure file

  let frontendResult ← runFrontend infile
  match frontendResult with
  | .error err =>
      IO.eprintln err
      return 1
  | .ok _ =>
      if cfg.typecheckOnly then
        return 0
      else
        writeEmitOutput cfg infile
        return 0
